# Generated by Django 2.1.7 on 2019-11-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='wallet_address',
            new_name='ip',
        ),
    ]
