# Generated by Django 2.1.7 on 2019-11-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchainapp', '0002_auto_20191130_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='ip',
            field=models.CharField(max_length=20),
        ),
    ]
